name: "SafeChat"
version: ${project.version}
main: studio.thevipershow.safechat.SafeChat
load: POSTWORLD
authors: [ TheViperShow, Jochyoua ]
softdepend: [ Vault ]
api-version: 1.13
description: "Keep your chat safe!"