name: "SafeChat"
version: ${version}
main: 'top.cmarco.safechat.SafeChat'
load: POSTWORLD
authors: [ CMarco , Jochyoua ]
softdepend: [ Vault ]
api-version: "1.13"
description: "Keep your chat safe!"
permissions:
  safechat.commands.help:
    default: true
  safechat.commands.version:
    default: true