name: "SafeChat"
version: ${project.version}
main: studio.thevipershow.safechat.SafeChat
api-version: "1.13"
load: STARTUP
authors: [TheViperShow]
softdepend: [Vault]
description: "Keep your chat safe!"
